package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF000000)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEAEAEA)
val md_theme_light_onPrimaryContainer = Color(0xFF141414)
val md_theme_light_secondary = Color(0xFF6B6B6B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF3F3F3)
val md_theme_light_onSecondaryContainer = Color(0xFF1F1F1F)
val md_theme_light_tertiary = Color(0xFF333333)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEBEBEB)
val md_theme_light_onTertiaryContainer = Color(0xFF141414)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_outline = Color(0xFFC7C7C7)
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF1A1A1A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1A1A1A)
val md_theme_light_surfaceVariant = Color(0xFFF4F4F4)
val md_theme_light_onSurfaceVariant = Color(0xFF5C5C5C)

val md_theme_dark_primary = Color(0xFFFFFFFF)
val md_theme_dark_onPrimary = Color(0xFF000000)
val md_theme_dark_primaryContainer = Color(0xFF262626)
val md_theme_dark_onPrimaryContainer = Color(0xFFE5E5E5)
val md_theme_dark_secondary = Color(0xFFA3A3A3)
val md_theme_dark_onSecondary = Color(0xFF1A1A1A)
val md_theme_dark_secondaryContainer = Color(0xFF333333)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCCCCC)
val md_theme_dark_tertiary = Color(0xFFE5E5E5)
val md_theme_dark_onTertiary = Color(0xFF1A1A1A)
val md_theme_dark_tertiaryContainer = Color(0xFF262626)
val md_theme_dark_onTertiaryContainer = Color(0xFFE5E5E5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF5C5C5C)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFE5E5E5)
val md_theme_dark_surface = Color(0xFF1E1E1E)
val md_theme_dark_onSurface = Color(0xFFE5E5E5)
val md_theme_dark_surfaceVariant = Color(0xFF252525)
val md_theme_dark_onSurfaceVariant = Color(0xFFA3A3A3)
